FROM node:18.12.1 AS build

WORKDIR /usr/src/app

RUN npm install -g @angular/cli@16.2.6

COPY package*.json ./

RUN npm install

COPY . .

RUN ng build --configuration=production --base-href=/ --output-path=dist

FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
